### ISSUE TITLE
Update to Chapter 4

### ISSUE THREAD

**Issue by burque505** [PacktPublishing/Hands-On-GUI-Application-Development-in-Go#1]
Thank you for fixing the code in Chapter Four. I'm uncertain now how this will affect Chapter Four in the book.
I have come to a dead stop at the following on page 81:
```
If you want to test this code, the easiest approach is to replace Dialog with MainWindow
and run it like the main layout (don't forget to change it back before moving on).
```
It's not intuitively clear to me what's meant there. If you replace Dialog with MainWindow, what does "run it like the main layout" mean?

**Comment by andydotxyz** [comment]
> Thank you for fixing the code in Chapter Four. I'm uncertain now how this will affect Chapter Four in the book.
> I have come to a dead stop at the following on page 81:

This is a good question, I am gathering the changes and if we produce an updated version of the book we will double-check all code changes that were made since publishing and update text references.

> It's not intuitively clear to me what's meant there. If you replace Dialog with MainWindow, what does "run it like the main layout" mean?

It means semantically I guess, that by using a `MainWindow` instead of a `Dialog` it will run like a main application window instead of a dialog within the app context. Dialogs require to be run from another window so this is just a quick workaround to test it quicker.
You can skip the hint and just carry on with the whole app :).

**Comment by burque505** [comment]
Thanks for your quick attention to the issue. Greatly appreciated.
